# Generated by Django 2.2.7 on 2019-11-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ar_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('model_type', models.CharField(default='OBJ', max_length=200)),
                ('scale_x', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('scale_y', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('scale_z', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('rot_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rot_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rot_z', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Image_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image_target_ar_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arify_app.Ar_object')),
                ('image_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arify_app.Image_target')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arify_app.Scene')),
            ],
        ),
        migrations.AddField(
            model_name='image_target',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arify_app.Scene'),
        ),
        migrations.AddField(
            model_name='ar_object',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arify_app.Scene'),
        ),
    ]
