# Generated by Django 2.2.7 on 2019-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_object',
            name='mtl_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
